#!/usr/bin/env bash
# Install ngnix
sudo apt-get -y update
sudo apt-get install -y nginx

# configuration
mkdir /etc/nginx/html

# creating sample page
echo "Hello World" > /etc/nginx/html/index.html

# creating server block files
echo "server {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /etc/nginx/html;
	index index.html index.htm index.nginx-debian.html;

	server_name _;
}
" > /etc/nginx/sites-available/default

# Restart Nginx
nginx -s reload
