#!/usr/bin/env bash
# Gives information about the school file

if [ -e "school" ]; then
    echo "school file exits"
    if [ -s "school" ]; then
	echo "school file is not empty"
    else
	echo "school file is empty"
    fi

    if [ -f "school" ]; then
